Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "coca cola")
Ingredient.create(name: "sugar")
Ingredient.create(name: "jet 27")
Ingredient.create(name: "vodka")
Ingredient.create(name: "whisky")
